---
vrf: 
    - name: I
      addr_fam: "ipv4 unicast"
      import_rt: "65921:769"
      export_rt: "65921:769"
      rd: "65921:769"
interface:
    - name: "Bundle-ether91"
      vrf: I
      prefix: 10.20.101.20/31
      description: "ASR5-leaf1-I"
      vlan: 2701
bgp:
    - local_asn: 65921
      neighbor:
           - ip: 10.20.101.21
             remote_asn: 65102
             description: leaf1
      sg:
           - name: "SG-LEAF-AS65102"
             description: "LEAF-SW EBGP"
      ng:
           - name: "NG-LEAF-AS65102"
rp:
    - in: "RP-AS65102-I-IN"
      out: "RP-AS65102-I-OUT"
