---
- name: Read data. Create interface report
  connection: local
  hosts: all
  vars: 
  - results: "{{inventory_dir}}/results"
  tasks:
  - import_tasks: "read-{{src|default('device')}}.yml"
  - import_tasks: "report-{{src|default('interface_device_j2')}}.yml"

