---
- name: Collect IOS-XR Facts from devices. Save them to file
  hosts: dc-gw
  connection: local
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - iosxr_facts:
      gather_subset: interfaces
  - lineinfile:
      dest: "{{results}}/interface_report.log"
#      regexp: "{{inventory_hostname}}"
#      line: "{{'%20s %8s'|format(ansible_net_interfaces,mtu)}}"
