---
- name: Collect IOS-XR Facts from devices. Save them to file
  hosts: dc-gw
  connection: local
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - iosxr_facts:
      gather_subset: all
  - snmp_facts:
      host: "{{ ansible_host }}"
      community: 2018
      version: v2
  - lineinfile:
      dest: "{{results}}/system_report.log"
      regexp: "{{ansible_sysname}}"
      line: "{{'%20s %8s %8s %8s'|format(ansible_sysname,ansible_sysdescr,ansible_sysuptime,ansible_net_memfree_mb)}}"
