---
- template:
    src: "/opt/net-automation/templates/interface-text.j2"
    dest: "{{results}}/interfaces.log"
  vars:
    allhosts: "{{hostvars}}"
  run_once: true
- copy:
    content={{hostvars | to_nice_yaml}} dest={{results}}/{{ansible_host}}-hostvars.log
#- debug: var=hostvars
#    msg: "The rabbit is: {{hostvars.stdout_lines}}"
