---
- file:
    path: "{{results}}/uptime.log"
    state: touch
  run_once: true
- lineinfile:
    dest: "{{results}}/uptime.log"
    regexp: "{{inventory_hostname}}"
    line: "{{inventory_hostname}} {{ansible_sysuptime}}"
